name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js and pnpm
      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v4

      # Cache node_modules
      - name: Cache node_modules
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      # Step 4: Install NX CLI globally
      - name: Install NX CLI
        run: pnpm add -g nx@latest

      # Step 5: Build all apps using the existing script
      - name: Build All Apps
        run: pnpm build:apps

      # Step 6: Deploy Podcast App
      - name: Deploy Podcast App to Vercel
        run: npx vercel --token=$VERCEL_TOKEN --prod dist/apps/podcast
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_PODCAST }}

      # Step 7: Deploy Shell App
      - name: Deploy Shell App to Vercel
        run: npx vercel --token=$VERCEL_TOKEN --prod dist/apps/shell
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_SHELL }}
